name: CI
# mainへのpush/手動によってworkflowがトリガー
on:
  push:
    branches: [main]
  workflow_dispatch:

# トップレベルのpermissionsはworkflow全体の既定値で、jobで上書き可能
permissions:
  contents: read

jobs:
  # repoをrunner上にcheckout -> 指定versionのgo runtimeを初期化 -> go testを実行
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go runtime
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test ./...

  # test job成功後、各serviceに対してdocker build実行
  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      # jobレベルのpermissions定義はworkflowレベルの定義を"置換"するので、contents: readの明示が必要
      contents: read
    strategy:
      fail-fast: true
      # matrix.<変数>の組み合わせ分jobが走る -> ここでは2回
      matrix:
        service: [document, post]
        # version: [v1, v2, v3] <- このような変数がある場合、2service * 3versionで6回jobが走る
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ap-northeast-1
          mask-aws-account-id: true

      - name: Login to ECR
        id: ecr # 出力値や実行結果を、job内の後続stepから参照するための識別子
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7

      - name: Compose image tag
        id: tagging
        run: |
            DATE=$(TZ=Asia/Tokyo date +%Y%m%d)
            SHA=${GITHUB_SHA::7}
            echo "tag=${DATE}-${SHA}" >> "$GITHUB_OUTPUT"
            echo "image=${{ steps.ecr.outputs.registry }}/tf-practice/${{ matrix.service }}-api" >> "$GITHUB_OUTPUT"

      - name: Build and push docker image
        run: |
            IMAGE="${{ steps.tagging.outputs.image }}:${{ steps.tagging.outputs.tag }}"
            docker build \
              --build-arg SERVICE_NAME=${{ matrix.service }} \
              -f docker/Dockerfile \
              -t "$IMAGE" \
              .
            docker push "$IMAGE"

  # GitHubからJWTを発行し、payload上のiss/aud/subを表示する(デバッグ用・testと並列実行)
  print-claim:
    runs-on: ubuntu-latest
    permissions:
      # permissinos.id-token = writeにより、JWT発行用の環境変数が埋め込まれる
      # - ACTIONS_ID_TOKEN_REQUEST_URL: job実行毎に払い出される専用URL
      # - ACTIONS_ID_TOKEN_REQUEST_TOKEN: ↑を叩くための短命bearer token
      id-token: write
    steps:
      - name: Print OIDC claim
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          # 1. runnerがACTIONS_ID_TOKEN_REQUEST_URL宛にJWT発行をリクエストする
          # 2. GitHubがACTIONS_ID_TOKEN_REQUEST_TOKENから実行jobを照合し、JWT payloadのclaimを構築し、秘密鍵で署名して返す
          script: |
            const token = await core.getIDToken('sts.amazonaws.com')
            const payload = token.split('.')[1]
            const { iss, aud, sub } = JSON.parse(
              Buffer.from(payload, 'base64url').toString()
            )
            // workflow実行結果ページに表を描画
            core.summary
              .addHeading('OIDC claims', 3)
              .addTable([
                [{data: 'claim', header: true}, {data:'value', header:true}],
                ['iss', iss],
                ['aud', aud],
                ['sub', sub]
              ])
              .write()
